#!/usr/bin/env python3
"""Defects of the published datasets, measured rather than assumed away.

Every other file here judges Talos -- our manifests, our windows, our labels.
This one judges the sources those labels describe, because two published facts
about the CIC datasets would quietly invalidate anything built on them if nobody
took a reading.

The first is an extraction defect. Rosay, Carlier, Cheval and Leroux (ICISSP
2022, the LYCOS-IDS2017 paper) traced four classes of artefact to CICFlowMeter,
the tool that produced the CSV feature tables every CIC dataset ships, and were
explicit about the blast radius: "We found that all datasets containing CSV
files generated by CICFlowMeter contain these artifacts." That covers
CIC-IDS-2017, CSE-CIC-IDS-2018 and CIC-DDoS-2019 -- all three of ours. Talos
reads none of those CSVs: the lake is Zeek output over the original pcaps. So
the artefacts should be ABSENT, and their absence is the point. It is the
difference between asserting that our features do not carry the defects the
published tables carry and having measured it, which is why
art.cicflowmeter_artefacts reports when it finds nothing. Here the negative
result IS the result, and staying silent would throw it away.

The second is a calendar error. CIC-DDoS-2019's published dates disagree with
the clocks inside its own captures by whole months, and a manifest transcribed
from the website rather than from the capture would put every attack window
outside the data entirely -- producing a complete, clean-looking labelled
dataset in which every flow is benign and nothing raises an error. Our manifest
already resolves it. art.date_anchor exists so that resolution stays measured
instead of remembered.

Both readings are about the source rather than about the schedule, which is why
they share a file across two tiers: the artefact probes are arithmetic over the
flows, the date anchor is a claim about the manifest.
"""

from datetime import datetime, timedelta, timezone

from src.label_validation.core.finding import Finding, Severity
from src.label_validation.core.registry import check

# CICFlowMeter reads an ARP frame as though it were IPv4, and the ARP header
# bytes it lands on read back as this pair of addresses. Neither is routable and
# no capture can legitimately contain them, so their presence identifies a flow
# table that came out of CICFlowMeter rather than out of a packet.
ARTEFACT_IPS = ("8.0.6.4", "8.6.0.1")

# What a protocol field holds when the extractor could not identify a transport
# and wrote a placeholder instead of naming one. Zeek writes 'unknown_transport'
# for exactly these packets and never a bare zero, so a zero here is a row Zeek
# did not produce.
DEGENERATE_PROTO = ("0", "", "unknown", "none")

# Zeek's numeric conn counters. Probe 1 has no literal translation (see the
# check); the generic symptom it describes -- a numeric column with zero
# variance across the whole dataset -- is measured over these.
NUMERIC_COUNTERS = ("duration", "orig_bytes", "resp_bytes", "missed_bytes",
                    "orig_pkts", "orig_ip_bytes", "resp_pkts", "resp_ip_bytes")

# Aggregates emitted per counter by the artefact scan: min, max, non-null count.
PER_COUNTER = 3


def _in_list(col, values):
    lit = ", ".join("'" + str(v).replace("'", "''") + "'" for v in values)
    return f'"{col}" IN ({lit})'


def _offset_tz(offset):
    """'-03:00' -> a fixed-offset tzinfo.

    The inverse of the offset handling in label_flows.epoch(): that turns a
    manifest's local wall clock into epoch seconds, this turns epoch seconds
    back into the local date the manifest wrote them as, so derived and asserted
    dates are compared in the same frame rather than across two.
    """
    text = str(offset or "+00:00")
    sign = -1 if text.startswith("-") else 1
    h, _, m = text.lstrip("+-").partition(":")
    return timezone(sign * timedelta(hours=int(h or 0), minutes=int(m or 0)))


@check(id="art.cicflowmeter_artefacts", tier=0,
       title="the published CICFlowMeter artefacts are absent from our extraction",
       needs=("labelled",), max_severity=Severity.MINOR)
def cicflowmeter_artefacts(ctx):
    """Four known CICFlowMeter defects, probed for in data Zeek produced.

    Rosay et al. (ICISSP 2022) rebuilt CIC-IDS2017 as LYCOS-IDS2017 after
    finding four artefact classes that CICFlowMeter injects into every CSV it
    writes -- "We found that all datasets containing CSV files generated by
    CICFlowMeter contain these artifacts" -- which places them in CIC-IDS-2017,
    CSE-CIC-IDS-2018 and CIC-DDoS-2019 alike:

      1. Bulk features computed through an integer division that always yields
         the same result, leaving those columns constant across the dataset.
      2. ARP frames parsed as IPv4 through an EtherType bug, producing flows
         between the addresses 8.0.6.4 and 8.6.0.1.
      3. Non-TCP/UDP IPv4 packets -- ICMP, IGMP, SCTP -- collapsed to protocol 0
         with source and destination port 0.
      4. TCP flows cut at the first FIN, so one connection is emitted as two
         records whose halves can fall either side of a label boundary, leaving
         the same connection benign in one row and attack in another.

    Talos reads none of those CSVs, so this check expects to find nothing and
    says so when it does. A hit would mean CSV-derived rows have entered the
    lake, and every feature in the affected zone would inherit a documented
    miscalculation.

    Probes 2 and 3 translate directly: both are values in columns Zeek also
    writes, and Zeek writes neither. Probe 4 translates in part. Zeek emits one
    record per connection, carries the whole flag sequence in `history` and the
    termination verdict in `conn_state`, so a connection cut at the first FIN
    cannot be produced here by construction; what remains testable is the
    visible consequence -- one connection appearing twice under two different
    labels -- and that is what is measured, over the TCP flows whose `history`
    shows a FIN in both directions. Probe 1 does not translate at all: Zeek has
    no bulk features and counts bytes and packets directly, with no integer
    division to get wrong. The generic symptom, a numeric column with zero
    variance, is measured and reported for the record but can never escalate
    here, because a constant Zeek counter is a fact about the traffic rather
    than evidence of this defect.
    """
    src = ctx.q("labelled")
    have = set(ctx.columns)

    ip_cols = [c for c in ("id.orig_h", "id.resp_h") if c in have]
    arp_expr = (" OR ".join(_in_list(c, ARTEFACT_IPS) for c in ip_cols)
                if ip_cols else None)

    port_cols = [c for c in ("id.orig_p", "id.resp_p") if c in have]
    degenerate_expr = None
    if "proto" in have and len(port_cols) == 2:
        proto_zero = ("proto IS NULL OR lower(CAST(proto AS VARCHAR)) IN ("
                      + ", ".join(f"'{v}'" for v in DEGENERATE_PROTO) + ")")
        ports_zero = " AND ".join(f'coalesce("{c}", 0) = 0' for c in port_cols)
        # Probe 3 is defined as the degenerate flows that are NOT the 8.0.6.4
        # family, so the two probes count disjoint populations and a single
        # defect cannot be reported twice.
        not_arp = f"NOT ({arp_expr})" if arp_expr else "true"
        degenerate_expr = f"(({proto_zero}) AND {ports_zero} AND {not_arp})"

    both_fin_expr = None
    if "history" in have:
        fins = ("history IS NOT NULL AND contains(history, 'F') "
                "AND contains(history, 'f')")
        both_fin_expr = f"(proto = 'tcp' AND {fins})" if "proto" in have else f"({fins})"

    counters = [c for c in NUMERIC_COUNTERS if c in have]
    null_bigint = "CAST(NULL AS BIGINT)"
    sel = [
        "count(*)",
        f"sum(CASE WHEN {arp_expr} THEN 1 ELSE 0 END)" if arp_expr else null_bigint,
        (f"sum(CASE WHEN {degenerate_expr} THEN 1 ELSE 0 END)"
         if degenerate_expr else null_bigint),
        ("sum(CASE WHEN proto = 'unknown_transport' THEN 1 ELSE 0 END)"
         if "proto" in have else null_bigint),
        (f"sum(CASE WHEN {both_fin_expr} THEN 1 ELSE 0 END)"
         if both_fin_expr else null_bigint),
    ]
    for c in counters:
        sel += [f'min("{c}")', f'max("{c}")', f'count("{c}")']
    q = (f"SELECT {', '.join(sel)}\n"
         f"FROM read_parquet('{src}', union_by_name = true)")
    row = ctx.lake.one(q)
    flows = int(row[0] or 0)
    arp, degenerate, unknown_transport, both_fin = (
        None if v is None else int(v) for v in row[1:5])

    # Probe 4's group-by only pays for itself where there is something to group:
    # on 2019's floods almost nothing reaches a bidirectional teardown.
    key_cols = [c for c in ("id.orig_h", "id.orig_p", "id.resp_h", "id.resp_p")
                if c in have]
    conflict_q, conflict_groups, conflict_flows = None, None, None
    if (both_fin and len(key_cols) == 4 and "ts" in have
            and "label_binary" in have):
        keys = ", ".join(f'"{c}"' for c in key_cols) + ", ts"
        conflict_q = f"""
        SELECT count(*) AS groups, coalesce(sum(n), 0) AS flows FROM (
            SELECT {keys}, count(*) AS n
            FROM read_parquet('{src}', union_by_name = true)
            WHERE {both_fin_expr}
            GROUP BY {keys}
            HAVING count(DISTINCT label_binary) > 1)"""
        conflict_groups, conflict_flows = (int(v) for v in ctx.lake.one(conflict_q))
    elif both_fin is not None:
        conflict_groups, conflict_flows = 0, 0

    limit = float(ctx.threshold("cicflowmeter_artefact_rate_max", 0.0))

    def rate(n):
        return round(n / flows, 12) if (flows and n is not None) else None

    probes = [
        {"probe": 2,
         "artefact": "ARP frames parsed as IPv4 (addresses 8.0.6.4 / 8.6.0.1)",
         "measured": ("flows whose id.orig_h or id.resp_h is one of the ARP "
                      "artefact addresses"),
         "flows": arp, "rate": rate(arp)},
        {"probe": 3,
         "artefact": "non-TCP/UDP IPv4 collapsed to protocol 0 with ports 0",
         "measured": ("flows with an absent or zero protocol and both ports "
                      "zero, excluding the 8.0.6.4 family"),
         "flows": degenerate, "rate": rate(degenerate)},
        {"probe": 4,
         "artefact": "TCP flow cut at the first FIN, halves labelled differently",
         "measured": ("connections with a FIN in both directions that appear "
                      "more than once under conflicting label_binary values"),
         "flows": conflict_flows, "rate": rate(conflict_flows),
         "conflicting_connections": conflict_groups,
         "bidirectional_fin_flows": both_fin},
    ]
    for p in probes:
        if p["flows"] is None:
            p["status"] = "not run: the labelled zone does not carry the columns it reads"
            p["verdict"] = "unmeasured"
        elif p["flows"] > 0 and (p["rate"] or 0) > limit:
            p["status"] = "ran"
            p["verdict"] = "PRESENT"
        else:
            p["status"] = "ran"
            p["verdict"] = "absent"

    constant = []
    for i, c in enumerate(counters):
        lo, hi, nonnull = row[5 + i * PER_COUNTER: 5 + (i + 1) * PER_COUNTER]
        if nonnull and lo is not None and lo == hi:
            constant.append({"probe": 1, "column": c, "constant_value": lo,
                             "non_null_flows": int(nonnull)})
    probes.insert(0, {
        "probe": 1,
        "artefact": "bulk features constant through an integer-division fault",
        "measured": ("no literal translation: Zeek has no bulk features. Numeric "
                     "counters with zero variance are reported instead and never "
                     "escalate"),
        "status": "does not translate", "verdict": "not applicable",
        "constant_numeric_columns": len(constant),
        "columns_examined": len(counters)})

    present = [p for p in probes if p["verdict"] == "PRESENT"]
    unmeasured = [p for p in probes if p["verdict"] == "unmeasured"]
    metrics = {
        "flows": flows,
        "artefact_rate_max": limit,
        "probes_run": sum(1 for p in probes if p["status"] == "ran"),
        "probes_present": len(present),
        "probes_unmeasured": len(unmeasured),
        "arp_artefact_flows": arp,
        "degenerate_protocol_flows": degenerate,
        "conflicting_termination_flows": conflict_flows,
        "conflicting_termination_connections": conflict_groups,
        "bidirectional_fin_flows": both_fin,
        # Zeek's correct representation of the very packets probe 3 says
        # CICFlowMeter collapses to protocol 0: they keep a named transport
        # instead. Descriptive, never a fault.
        "unknown_transport_flows": unknown_transport,
        "constant_numeric_columns": len(constant),
    }
    evidence = probes + constant
    scope = {"source": "Rosay et al., ICISSP 2022 (LYCOS-IDS2017)",
             "extractor_under_test": "Zeek", "extractor_at_fault": "CICFlowMeter"}
    repro = q if not conflict_q else q + ";\n" + conflict_q.strip()

    if present:
        return [Finding(
            check_id="art.cicflowmeter_artefacts", dataset=ctx.dataset,
            severity=Severity.MINOR,
            title=f"{len(present)} CICFlowMeter artefact signature(s) present in the "
                  f"labelled zone",
            detail="These signatures belong to CICFlowMeter, the tool that produced the "
                   "CSV feature tables shipped with every CIC dataset, and Rosay et al. "
                   "(ICISSP 2022) found them in all of them. Talos extracts from the "
                   "pcaps with Zeek instead, so none of them should be reachable here. "
                   "Their presence means rows derived from the published CSVs have "
                   "entered the lake, and every feature computed over the affected flows "
                   "inherits a documented miscalculation rather than a measurement.",
            metrics=metrics, evidence=evidence, scope=scope, repro=repro)]

    return [Finding(
        check_id="art.cicflowmeter_artefacts", dataset=ctx.dataset,
        severity=Severity.INFO,
        title=f"CICFlowMeter artefact probes ran over {flows:,} flows and found "
              f"none of the signatures",
        detail="Reported because the negative result is the finding. Rosay et al. "
               "(ICISSP 2022) identified four artefact classes that CICFlowMeter writes "
               "into every CSV it generates -- constant bulk features from an integer "
               "division, ARP frames read as IPv4 traffic between 8.0.6.4 and 8.6.0.1, "
               "non-TCP/UDP packets collapsed to protocol 0 with ports 0, and TCP flows "
               "cut at the first FIN whose halves can end up labelled differently -- and "
               "stated that every dataset shipping CICFlowMeter CSVs carries them, "
               "CIC-IDS-2017, CSE-CIC-IDS-2018 and CIC-DDoS-2019 included. Talos does "
               "not use those CSVs; the lake is Zeek output over the original pcaps. "
               "This check is the measurement behind that claim, so that 'our features "
               "do not carry the published artefacts' is a reading rather than an "
               "assertion. Probe 1 has no literal equivalent in Zeek's schema and is "
               "reported as inapplicable rather than faked."
               + (f" {len(unmeasured)} probe(s) could not run for want of a column and "
                  f"are recorded as unmeasured, not as clean." if unmeasured else ""),
        metrics=metrics, evidence=evidence, scope=scope, repro=repro)]


@check(id="art.date_anchor", tier=1,
       title="capture clocks agree with the dates the manifest asserts",
       datasets=("cic-ddos-2019",), needs=("labelled",),
       max_severity=Severity.BLOCKER)
def date_anchor(ctx):
    """CIC-DDoS-2019's published calendar is not the calendar its captures ran on.

    The dataset is named 2019 and its web page presents the two capture days as
    January 12th and March 11th. The clocks inside the captures say otherwise,
    and two independent sources confirm it. The FKIE COMIDDS catalogue quotes a
    row of the distributed `CSVs/CSV-03-11/Portmap.csv` carrying
    `Timestamp = 2018-11-03 10:01:35.983831`; CICFlowMeter issue #69 reports the
    website's "training day January 12th" against pcap timestamps that read
    December 1st. The coherent reading is that the folder names are capture
    dates written DD-MM while the website re-presents them as MM-DD in 2019:
    `CSV-03-11` is 2018-11-03 and `CSV-01-12` is 2018-12-01. The times of day
    are valid; the dates are not.

    That distinction carries the entire risk. A manifest transcribed from the
    website would hold the right hours against the wrong months, so every window
    would fall outside its capture, every rule would match zero flows, and the
    labelling stage would write a complete and clean-looking dataset in which
    every flow is benign -- with nothing anywhere raising an error.

    src/preprocess/manifests/cic-ddos-2019.yaml already resolves this, using
    2018-11-03 and 2018-12-01, so on the real data this check passes. It is
    written for the future edit that reintroduces the website dates: for every
    capture it derives the date the flows were actually recorded on and compares
    it against the date the manifest asserts for that capture. A delta of months
    is a BLOCKER, because it is precisely the silent total failure above.
    Agreement is reported too, at INFO, so a passing anchor is visible evidence
    rather than an absence.
    """
    if "capture" not in ctx.columns or "ts" not in ctx.columns:
        return []
    src = ctx.q("labelled")

    # What the manifest asserts, straight from the document rather than from the
    # normalised rules: the folder-to-day mapping must be checkable even when no
    # rule fires, which is exactly the state a wrong date produces.
    asserted = {}
    for key, day in (ctx.manifest.get("days") or {}).items():
        folder = str(day.get("lake_folder") or "").strip()
        if folder:
            asserted[folder] = {"manifest_day": key, "asserted_date": str(day.get("date")),
                                "utc_offset": str(day.get("utc_offset") or "+00:00"),
                                "asserted_by": "manifest days[].lake_folder"}

    q_days = f"""
    SELECT capture,
           strftime(to_timestamp(ts) AT TIME ZONE 'UTC', '%Y-%m-%d') AS utc_date,
           count(*) AS n, min(ts) AS ts_min, max(ts) AS ts_max
    FROM read_parquet('{src}', union_by_name = true)
    WHERE ts IS NOT NULL
    GROUP BY 1, 2 ORDER BY 1, 3 DESC"""
    captures = {}
    for cap, day, n, lo, hi in ctx.lake.sql(q_days):
        rec = captures.setdefault(str(cap), {"days": {}, "flows": 0,
                                             "ts_min": lo, "ts_max": hi})
        rec["days"][str(day)] = rec["days"].get(str(day), 0) + int(n)
        rec["flows"] += int(n)
        rec["ts_min"] = min(rec["ts_min"], lo)
        rec["ts_max"] = max(rec["ts_max"], hi)
    if not captures:
        return []

    # Which rules actually landed in each capture. A wrong date shows up here as
    # zero rules fired, which is the consequence the delta predicts.
    rule_date = {r["rid"]: r["date"] for r in ctx.rules}
    fired = {}
    q_rules = None
    if "rule_id" in ctx.columns:
        q_rules = f"""
        SELECT capture, rule_id, count(*) AS n
        FROM read_parquet('{src}', union_by_name = true)
        WHERE rule_id IS NOT NULL GROUP BY 1, 2"""
        for cap, rid, n in ctx.lake.sql(q_rules):
            f = fired.setdefault(str(cap), {"dates": {}, "rules": set(), "flows": 0})
            day = rule_date.get(int(rid))
            if day:
                f["dates"][day] = f["dates"].get(day, 0) + int(n)
            f["rules"].add(int(rid))
            f["flows"] += int(n)

    max_delta = int(ctx.threshold("date_anchor_max_delta_days", 0))
    blocker_delta = int(ctx.threshold("date_anchor_blocker_delta_days", 28))

    rows, unanchored = [], []
    for cap in sorted(captures):
        rec = captures[cap]
        derived_utc = max(rec["days"].items(), key=lambda kv: kv[1])[0]
        f = fired.get(cap, {"dates": {}, "rules": set(), "flows": 0})

        claim = None
        for folder, a in asserted.items():
            if folder == cap or (folder and cap and (folder in cap or cap in folder)):
                claim = dict(a)
                break
        if claim is None and f["dates"]:
            # No folder mapping: fall back to the dates of the rules that did
            # land here, which is weaker evidence and is labelled as such.
            top = max(f["dates"].items(), key=lambda kv: kv[1])[0]
            claim = {"manifest_day": None, "asserted_date": top,
                     "utc_offset": "+00:00",
                     "asserted_by": "dates of the rules that fired in this capture"}

        base = {"capture": cap, "flows": rec["flows"],
                "ts_min": rec["ts_min"], "ts_max": rec["ts_max"],
                "derived_utc_date": derived_utc,
                "utc_days_touched": len(rec["days"]),
                "rules_fired": len(f["rules"]), "attack_flows": f["flows"]}
        if claim is None:
            unanchored.append(dict(base, asserted_date=None,
                                   asserted_by="nothing in the manifest names this capture"))
            continue

        tz = _offset_tz(claim["utc_offset"])
        mid = (rec["ts_min"] + rec["ts_max"]) / 2.0
        derived_local = datetime.fromtimestamp(mid, tz).date()
        asserted_date = datetime.strptime(claim["asserted_date"], "%Y-%m-%d").date()
        rows.append(dict(base, **claim,
                         derived_local_date=derived_local.isoformat(),
                         delta_days=(derived_local - asserted_date).days,
                         delta_days_utc=(datetime.strptime(derived_utc, "%Y-%m-%d").date()
                                         - asserted_date).days))

    broken = [r for r in rows if abs(r["delta_days"]) > max_delta]
    repro = q_days.strip() + (";\n" + q_rules.strip() if q_rules else "")

    if broken:
        months = [r for r in broken if abs(r["delta_days"]) >= blocker_delta]
        worst = max(broken, key=lambda r: abs(r["delta_days"]))
        return [Finding(
            check_id="art.date_anchor", dataset=ctx.dataset,
            severity=Severity.BLOCKER if months else Severity.CRITICAL,
            title=f"{len(broken)} capture(s) were recorded on a different date than "
                  f"the manifest asserts (worst: {worst['capture']} off by "
                  f"{worst['delta_days']:+d} day(s))",
            detail="The manifest's dates and the capture clocks disagree. Labelling "
                   "converts each window's local wall-clock time to epoch seconds using "
                   "the asserted date, so a wrong date moves every window by that many "
                   "days: the windows land outside the capture, no rule matches "
                   "anything, and the labelling stage still writes a complete dataset in "
                   "which every flow is benign. CIC-DDoS-2019 is the known case -- its "
                   "web page presents the capture days as January 12th and March 11th "
                   "2019 while the captures themselves read 2018-12-01 and 2018-11-03. "
                   "The folder names are DD-MM capture dates; the website re-reads them "
                   "as MM-DD in 2019. Confirmed independently by the FKIE COMIDDS "
                   "catalogue, which quotes CSVs/CSV-03-11/Portmap.csv carrying "
                   "Timestamp = 2018-11-03 10:01:35.983831, and by CICFlowMeter issue "
                   "#69, which reports the site's 'January 12th' training day against "
                   "pcap timestamps reading December 1st. The times of day are valid; "
                   "the dates are not."
                   + (" The deltas here are whole months, which is the total-failure "
                      "case: nothing can be labelled at all." if months else
                      " The delta is under a month, so some windows may still overlap "
                      "the capture -- which is worse to read, not better."),
            metrics={"captures": len(rows) + len(unanchored),
                     "captures_mismatched": len(broken),
                     "captures_off_by_months": len(months),
                     "worst_delta_days": worst["delta_days"],
                     "max_delta_days_allowed": max_delta,
                     "blocker_delta_days": blocker_delta,
                     "captures_unanchored": len(unanchored),
                     **{f"delta_days_{r['capture']}": r["delta_days"] for r in rows}},
            evidence=broken + [r for r in rows if r not in broken] + unanchored,
            scope={"anchor": "flow timestamps vs manifest days[].date"},
            repro=repro)]

    return [Finding(
        check_id="art.date_anchor", dataset=ctx.dataset, severity=Severity.INFO,
        title=f"{len(rows)} capture(s) were recorded on exactly the dates the "
              f"manifest asserts",
        detail="Recorded because this one is worth being able to point at. "
               "CIC-DDoS-2019's published calendar does not match its own capture "
               "clocks: the site presents the two days as January 12th and March 11th "
               "2019, while the flows read 2018-12-01 and 2018-11-03. The folder names "
               "CSV-01-12 and CSV-03-11 are capture dates written DD-MM, which the "
               "website re-presents as MM-DD in 2019. Two independent confirmations: "
               "the FKIE COMIDDS catalogue quotes CSVs/CSV-03-11/Portmap.csv carrying "
               "Timestamp = 2018-11-03 10:01:35.983831, and CICFlowMeter issue #69 "
               "reports the site's 'January 12th' against pcap timestamps reading "
               "December 1st. Our manifest uses the capture dates, and the flows agree "
               "with it to the day. Had it used the published ones, every window would "
               "sit months away from the traffic and every rule would match zero flows "
               "while the pipeline reported success."
               + (f" {len(unanchored)} capture(s) have no date assertion to check "
                  f"against and are listed unresolved." if unanchored else ""),
        metrics={"captures": len(rows) + len(unanchored),
                 "captures_mismatched": 0,
                 "captures_unanchored": len(unanchored),
                 "max_delta_days_allowed": max_delta,
                 "blocker_delta_days": blocker_delta,
                 **{f"delta_days_{r['capture']}": r["delta_days"] for r in rows},
                 **{f"rules_fired_{r['capture']}": r["rules_fired"] for r in rows}},
        evidence=rows + unanchored,
        scope={"anchor": "flow timestamps vs manifest days[].date"},
        repro=repro)]
